### ISSUE TITLE
centos7 x64安装ok，但opencc那块有些问题

### ISSUE THREAD

**Issue by csx163** [onestraw/qiming#2]
已经yum install opencc opencc-tools opencc-devel
已经手动安装好distribute
已经pip install opencc-python
最后出现以下报错，希望大佬看看，谢谢。

[root@VM_164_229_centos qiming-master]# ./qm.py --test
OpenCC initialization error
Configuration error
Can not access configuration file: No such file or directory

Traceback (most recent call last):
  File "./qm.py", line 74, in <module>
    main()
  File "./qm.py", line 67, in main
    print(RenderName(names))
  File "./qm.py", line 22, in RenderName
    row = [i, t2s(n), s2t(n), toPY(n), toID(n),
  File "/root/code/pyt/qiming-master/view/opencc.py", line 21, in t2s
    return convert(text, 't2s')
  File "/root/code/pyt/qiming-master/view/opencc.py", line 12, in convert
    format(proc.returncode))
RuntimeError: Failed to call opencc with exit code 1

**Comment by onestraw** [comment]
1. 看错误好像是没找到 opencc的配置文件，执行qm.py前先确保 opencc 安装配置成功

2. 这里没有使用opencc-python，因为安装比较繁琐。

**Comment by csx163** [comment]
确实因为yum的opencc无法使用，后来编译一个后成功运行。
